core_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import editStatusView

app_name = 'core_app'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('report_incident/', views.report_incident, name='report_incident'),
    path('home/', views.home, name='home'),
    path('report/', views.report, name='report'),
    path('getIncident/', views.getIncident, name='getIncident'),
    path('edit_status/<int:incident_id>/', editStatusView.as_view(), name='edit_status'),
]

core_app/models.py
# models.py
from django.db import models


class Incident(models.Model):
    id = models.AutoField(primary_key=True)
    location = models.CharField(max_length=255, null=True)
    description = models.CharField(max_length=255, null=True)
    images = models.ImageField(upload_to='incident_images/', blank=True, null=True)
    incident_type = models.CharField(max_length=255, null=True)
    occur_time = models.DateTimeField()
    status = models.CharField(max_length=255, null=True)
    traffic_status = models.CharField(max_length=255, null=True)
    scale_impact = models.CharField(max_length=255, null=True)
    #lat_lng = models.CharField(max_length=255, null=True)
    extrainfo = models.JSONField()
    class Meta:
        db_table = 'incident'


class User(models.Model):
    email = models.CharField(max_length=255, null=True)
    password = models.CharField(max_length=255, null=True)
    role = models.CharField(max_length=255, null=True)
    class Meta:
        db_table = 'user'


class Image(models.Model):
    image = models.ImageField(upload_to='incident_images/', blank=True, null=True)
    class Meta:
        db_table = 'image'

core_app/forms.py
from django import forms
from core_app.models import Incident


class IncidentStatusForm(forms.ModelForm):
    class Meta:
        model = Incident
        fields = ['status']  # Add other fields as needed

core_app/views.py
from django.http import HttpResponse, JsonResponse
from core_app.models import Incident, Image, User
from django.shortcuts import render, redirect, get_object_or_404
import time
import sys
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views import View
import core_app.utils.auto_send_email as auto_send_email

sys.path.append('core_app/utils')


@method_decorator(csrf_exempt, name='dispatch')
class editStatusView(View):
    def post(self, request, incident_id):
        try:
            new_status = request.POST.get('status')
            incident = Incident.objects.get(pk=incident_id)
            incident.status = new_status
            incident.save()
            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'errors': str(e)})

def index(request):
    return HttpResponse("Report Success!")


def home(request):
    return render(request, "core_app/Home.html")

def report(request):
    return render(request, "core_app/Report.html")

def showIncident(request):
    return render(request, "core_app/Incident.html")


def user_login(request):
    if request.method == "POST":
        name = request.POST.get("uname", None)
        psw = request.POST.get("psw", None)

    return render(request, "core_app/Login.html")


receivers = ['dardat@tcd.ie', 'habeebra@tcd.ie', 'pedgaoks@tcd.ie', 'wangx33@tcd.ie', 'zhangj20@tcd.ie', 'welin@tcd.ie']


def report_incident(request):
    if request.method == "POST":
        id = None
        location = request.POST.get("location", None)
        description = request.POST.get("description", None)
        image_list = request.FILES.getlist('images')
        image = None
        for img in image_list:
            image = img

        incident_type = request.POST.get("category", None)
        occur_time = time.strftime('%Y-%m-%d', time.localtime(time.time()))
        status = "active"
        traffic_status = "crowded"
        scale_impact = request.POST.get("impactScale", None)
        incident = Incident(id=id, location=location,description=description, images=image, incident_type=incident_type,
                            occur_time=occur_time,
                            status=status,traffic_status=traffic_status,scale_impact=scale_impact)
        incident.save()
        # for image in image_list:
        #     img_instance = Image(image=image)
        #     img_instance.save()
        #     incident.images.add(img_instance)
        print(image)
        auto_send_email.send_email(f"\nLocation: {location} \nIncident-type:{incident_type} \nDescription: {description} \nStatus: {status}", receivers)
    return render(request, "core_app/Report.html")
    #return redirect("core_app:getIncident")
    # response_data = {'success': True, 'message': 'Report Success！'}
    # return JsonResponse(response_data)



def getIncident(request):
    incidents = Incident.objects.all()
    for incident in incidents:
        print(f"{incident.images.url}")
    return render(request, 'core_app/Incident.html', {'incidents': incidents})


def getUsers():
    users = User.objects.all()
    return users

core_app/templates/core_app/Home.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            padding-top: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            z-index: 1000;
            height: 60px;
            padding: 10px 20px;
            text-align: center;
            background: #4CAF50;
            color: white;
        }

        .header a {
            padding: 10px 15px;
            color: white;
            text-decoration: none;
            display: inline-block;
            cursor: pointer;
            font-size: 18px;
        }

        .header a:hover {
            background: #ddd;
            color: black;
        }

        .content {
            position: relative;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            display: none;
            height: calc(100vh - 80px);
            padding: 15px;
        }

        #home {
            display: block;
        }

        #map {
            height: 100%;
            width: 100%;
        }

    </style>
</head>
<body>

<div id="home" class="content">
    <div id="map"></div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    var map

    $(document).ready(function(){
        $(".header a").click(function(){
            var target = $(this).data("target");
            $(".content").hide();
            $(target).show();
        });
    });

    function validateForm() {
        var form = document.getElementById("reportForm");
        var errorMessage = document.getElementById("errorMessage");

        if (form.checkValidity()) {
            errorMessage.innerHTML = "";
            return true;
        } else {
            errorMessage.innerHTML = "Please fill in all required fields.";
            return false;
        }
    }

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                showPosition(position); 
                initMap(position); 
            }, function(error) {
                document.getElementById('location').value = "Can not get your location";
            });
        } else { 
            document.getElementById('location').value = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {
        var lat = position.coords.latitude;
        var lng = position.coords.longitude;
        reverseGeocode(lat, lng);
    }

    function reverseGeocode(lat, lng) {
        var geocoder = new google.maps.Geocoder();
        var latlng = {lat: parseFloat(lat), lng: parseFloat(lng)};

        geocoder.geocode({'location': latlng}, function(results, status) {
            if (status === 'OK') {
                if (results[0]) {
                    document.getElementById('location').value = results[0].formatted_address;
                } else {
                    document.getElementById('location').value = 'No address found';
                }
            } else {
                document.getElementById('location').value = 'Geocoder failed due to: ' + status;
            }
        });
    }

    function initMap() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                var noPoi = [
                    {
                        featureType: "poi",
                        stylers: [{ visibility: "off" }]  // 隐藏点兴趣
                    },
                    {
                        featureType: "transit",
                        elementType: "labels.icon",
                        stylers: [{ visibility: "off" }]  // 选择性隐藏公共交通标记，如果需要
                    }
                ];

                map = new google.maps.Map(document.getElementById('map'), {
                    center: pos,
                    zoom: 16,
                    styles:noPoi
                });

                var userMarker = new google.maps.Marker({
                    position: pos,
                    map: map,
                    title: "Your Location"
                });

                var disasters = [
                    { lat: pos.lat + 0.001, lng: pos.lng + 0.001, title: 'Fire' },
                    { lat: pos.lat - 0.001, lng: pos.lng - 0.001, title: 'Fire' },
                    { lat: pos.lat + 0.002, lng: pos.lng - 0.002, title: 'Fire' },
                ];

                disasters.forEach(function(disaster) {
                    var marker = new google.maps.Marker({
                        position: {lat: disaster.lat, lng: disaster.lng},
                        map: map,
                        title: disaster.title,
                        icon: { 
                           url: "/static/core_app/fire.svg",
                           scaledSize: new google.maps.Size(30, 30),
                           fillColor: '#ff0000'
                        }
                    });
                });
            }, function() {
                handleLocationError(true, map.getCenter());
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false);
        }
    }

    function handleLocationError(browserHasGeolocation, pos) {
        map = new google.maps.Map(document.getElementById('map'), {
            center: pos,
            zoom: 14
        });
        var infoWindow = new google.maps.InfoWindow({map: map});
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                            'Error: The Geolocation service failed.' :
                            'Error: Your browser doesn\'t support geolocation.');
    }

    window.onload = function() {
        getLocation();
    };

</script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqWMFEzFkRbi6w5hGgLVN3wEAwZsTURlM&callback=initMap">
</script>

</body>
</html>

core_app/templates/core_app/Incident.html
<!-- incident_list.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Incident List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'core_app/styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>

<div class="container-fluid mt-3">

    <!-- Refresh Button -->
    <div class="float-right mb-3">
        <button type="button" class="btn btn-primary" onclick="refreshData()" style="background-color: #3498db; color: #ffffff; border: 2px solid #3498db;">
            <i class="fas fa-sync-alt"></i> Refresh
        </button>
    </div>

<!--    <h1 class="mb-4">Incident List</h1>-->

    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Location</th>
                <th>Description</th>
                <th>Images</th>
                <th>Incident Type</th>
                <th>Timestamp</th>
                <th>Status</th>
                <th>Traffic</th>
                <th>Impact</th>
                <th>Modify</th>
            </tr>
        </thead>
        <tbody>
            {% for incident in incidents %}
                <tr>
                    <td class="align-middle">{{ incident.id }}</td>
                    <td class="align-middle">{{ incident.location }}</td>
                    <td class="align-middle">{{ incident.description }}</td>
                    <td class="align-middle">
<!--                    {% for image in incident.image %}-->
<!--                        <img src="{{ incident.image.url }}" alt="{{ incident.description }}">-->
<!--                        <p>{{ image.url }}</p>-->
<!--                    {% endfor %}-->
                        <img src="{{ incident.images.url }}" alt="{{ incident.description }}" style="width: 100px; height: 100px;">
                    </td>
                    <td class="align-middle">{{ incident.incident_type }}</td>
                    <td class="align-middle">{{ incident.occur_time }}</td>
                    <td class="align-middle">
                        <span id="status{{ incident.id }}">{{ incident.status }}</span>
                        <input type="text" id="statusInput{{ incident.id }}" style="display: none;">
                    </td>
                    <td class="align-middle">{{ incident.traffic_status }}</td>
                    <td class="align-middle">{{ incident.scale_impact }}</td>
                    <td class="align-middle center-buttons">
                        <button class="btn btn-sm btn-primary" onclick="editStatus('{{ incident.id }}')">Update</button>
                        <button class="btn btn-sm btn-success" onclick="confirmStatus('{{ incident.id }}')">Confirm</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

</body>
<script>
    function refreshData() {
        $.ajax({
            url: "{% url 'core_app:getIncident' %}",
            method: "GET",
            success: function(response) {
                location.reload();
            },
            error: function(error) {
                console.log("Error refreshing data:", error);
            }
        });
    }

    function confirmStatus(id) {
        const newStatus = document.getElementById("statusInput" + id).value;

        const csrftoken = getCookie('csrftoken');

        $.ajax({
            url: `/core_app/edit_status/${id}/`,
            type: "POST",
            data: { 'status': newStatus },
            headers: { 'X-CSRFToken': csrftoken },
            success: function(response) {
                if (response.success) {
                    document.getElementById("status" + id).innerText = newStatus;
                    document.getElementById("status" + id).style.display = "block";
                    document.getElementById("statusInput" + id).style.display = "none";
                } else {
                    console.log("Error:", response.errors);
                }
            },
            error: function(error) {
                console.log("Error:", error);
            }
        });
    }

    function editStatus(id) {
        document.getElementById("status" + id).style.display = "none";
        document.getElementById("statusInput" + id).style.display = "block";
        document.getElementById("statusInput" + id).value = document.getElementById("status" + id).innerText;
        document.getElementById("statusInput" + id).focus();
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>

</html>

core_app/templates/core_app/Login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
        }

        .container {
            max-width: 300px;
            width: 90%;
            padding: 16px;
            background-color: white;
            margin: 0 auto;
            margin-top: 50px;
            border: 1px solid black;
            border-radius: 4px;
        }

        input[type=text], input[type=password] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            opacity: 0.8;
        }

        a {
            color: #4CAF50;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

        @media (max-width: 600px) {
            .container {
                margin-top: 20px;
            }

            input[type=text], input[type=password], button {
                padding: 15px;
                font-size: 16px;
            }
        }
    </style>
</head>
<body>

<div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <button type="submit">Login</button>
    <a href="Register.html" style="display: block; text-align: center; margin-top: 10px;">Register</a>
</div>

</body>
</html>

core_app/templates/core_app/Register.html
<!DOCTYPE html>
<html>
<head>
    <title>Register Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f7f7f7;
        }

        .container {
            max-width: 300px;
            width: 90%;
            padding: 16px;
            background-color: white;
            border: 1px solid black;
            border-radius: 4px;
        }

        input[type=text], input[type=password] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            opacity: 0.8;
        }

        @media (max-width: 600px) {
            input[type=text], input[type=password], button {
                padding: 15px;
                font-size: 16px;
            }
        }
    </style>
    <script>
        function validateForm() {
            var psw = document.forms["myForm"]["psw"].value;
            var psw_repeat = document.forms["myForm"]["psw-repeat"].value;
            var uname = document.forms["myForm"]["uname"].value;

            if (psw != psw_repeat) {
                alert("Passwords do not match. Please re-enter your passwords.");
                return false;
            }

            if (psw.length < 8) {
                alert("Password should be at least 8 characters.");
                return false;
            }

            var regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
            if (!regex.test(uname)) {
                alert("Please enter a valid email address.");
                return false;
            }
            return true;
        }
    </script>
</head>
<body>

<div class="container">
    <form name="myForm" action="/submit_register" onsubmit="return validateForm()" method="post">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>

        <label for="psw-repeat"><b>Repeat Password</b></label>
        <input type="password" placeholder="Repeat Password" name="psw-repeat" required>

        <button type="submit">Register</button>
    </form>
</div>

</body>
</html>

core_app/templates/core_app/Report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        form {
            width: calc(100% - 40px);
            max-width: 600px;
            margin: 20px auto;
            background: #f4f4f4;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        form label {
            display: block;
            margin-bottom: 10px;
            font-size: 18px;
            color: #333;
        }

        form select, form input, form textarea {
            width: 100%;
            padding: 15px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }

        form select, form input, form textarea, form button {
            box-sizing: border-box;
        }

        form button {
            background: #4CAF50;
            color: white;
            padding: 15px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 18px;
            margin-top: 10px;
        }

        form button:hover {
            background: #369943;
        }

        .error-message {
            color: #d9534f;
            margin-top: 5px;
            font-size: 14px;
        }
 input[type="file"] {
    display: none;
  }

  /* 自定义样式的上传按钮 */
  .custom-file-upload {
    display: inline-block;
    padding: 10px 15px;
    cursor: pointer;
    font-size: 16px;
    font-weight: bold;
    color: #fff;
    background-color: #3498db;
    border: 1px solid #3498db;
    border-radius: 5px;
  }

  /* 鼠标悬停时的样式 */
  .custom-file-upload:hover {
    background-color: #2980b9;
    border-color: #2980b9;
  }
    </style>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

</head>
<body>
<div id="report" class="content">
    <form id="reportForm" onsubmit="return validateForm()" action="{% url 'core_app:report_incident' %}" method="post">
        <label for="category">Category:</label>
        <select id="category" name="category" required>
            <option value="" disabled selected>Select</option>
            <option value="Fire">Fire</option>
            <option value="Flood">Flood</option>
            <option value="Accident">Accident</option>
            <option value="Earthquake">Earthquake</option>
            <option value="Wildfire">Wildfire</option>
            <option value="Cyclones">Cyclones</option>
            <option value="Industrial Accident">Industrial Accident</option>
            <option value="Transportation Accident">Transportation Accident</option>
            <option value="Structural Failure">Structural Failure</option>
            <option value="Nuclear Incident">Nuclear Incident</option>
            <option value="Biological Incident">Biological Incident</option>
            <option value="Chemical Incident">Chemical Incident</option>
            <option value="Toxic Waste Incident">Toxic Waste Incident</option>
            <option value="Electric Incidents">Electric Incidents</option>
        </select>

        <label for="location">Location:</label>
        <input type="text" id="location" name="location" placeholder="Enter location" readonly required>

        <label for="images" class="custom-file-upload">Images of incident:</label>
        <input type="file" id="images" name="images" accept="image/*" multiple required>

        <label for="impactScale">Impact Scale:</label>
        <select id="impactScale" name="impactScale" required>
            <option value="" disabled selected>Select</option>
            <option value="Mild">Mild</option>
            <option value="Severe">Severe</option>
        </select>

        <label for="description">Description:</label>
        <textarea id="description" name="description" placeholder="Enter description" required></textarea>

        <button type="submit"class="btn btn-primary" style="background-color: #3498db; color: #ffffff; border: 2px solid #3498db;">
            <i class="fas fa-sync-alt"></i>Submit</button>
        <div class="error-message" id="errorMessage"></div>
    </form>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
<script>
    var map

    $(document).ready(function(){
        $(".header a").click(function(){
            var target = $(this).data("target");
            $(".content").hide();
            $(target).show();
        });
    });

    function validateForm() {
        var form = document.getElementById("reportForm");
        var errorMessage = document.getElementById("errorMessage");

        if (form.checkValidity()) {
            errorMessage.innerHTML = "";
            return true;
        } else {
            errorMessage.innerHTML = "Please fill in all required fields.";
            return false;
        }
    }

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                showPosition(position);
                initMap(position);
            }, function(error) {
                document.getElementById('location').value = "Can not get your location";
            });
        } else {
            document.getElementById('location').value = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {
        var lat = position.coords.latitude;
        var lng = position.coords.longitude;
        reverseGeocode(lat, lng);
    }

    function reverseGeocode(lat, lng) {
        var geocoder = new google.maps.Geocoder();
        var latlng = {lat: parseFloat(lat), lng: parseFloat(lng)};

        geocoder.geocode({'location': latlng}, function(results, status) {
            if (status === 'OK') {
                if (results[0]) {
                    document.getElementById('location').value = results[0].formatted_address;
                } else {
                    document.getElementById('location').value = 'No address found';
                }
            } else {
                document.getElementById('location').value = 'Geocoder failed due to: ' + status;
            }
        });
    }

    function initMap() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                var noPoi = [
                    {
                        featureType: "poi",
                        stylers: [{ visibility: "off" }]  // 隐藏点兴趣
                    },
                    {
                        featureType: "transit",
                        elementType: "labels.icon",
                        stylers: [{ visibility: "off" }]  // 选择性隐藏公共交通标记，如果需要
                    }
                ];

                map = new google.maps.Map(document.getElementById('map'), {
                    center: pos,
                    zoom: 16,
                    styles:noPoi
                });

                var userMarker = new google.maps.Marker({
                    position: pos,
                    map: map,
                    title: "Your Location"
                });

                var disasters = [
                    { lat: pos.lat + 0.001, lng: pos.lng + 0.001, title: 'Fire' },
                    { lat: pos.lat - 0.001, lng: pos.lng - 0.001, title: 'Fire' },
                    { lat: pos.lat + 0.002, lng: pos.lng - 0.002, title: 'Fire' },
                ];

                disasters.forEach(function(disaster) {
                    var marker = new google.maps.Marker({
                        position: {lat: disaster.lat, lng: disaster.lng},
                        map: map,
                        title: disaster.title,
                        icon: {
                           url: "/core_app/static/core_app/fire.svg",
                           scaledSize: new google.maps.Size(30, 30)
                        }
                    });
                });
            }, function() {
                handleLocationError(true, map.getCenter());
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false);
        }
    }

    function handleLocationError(browserHasGeolocation, pos) {
        map = new google.maps.Map(document.getElementById('map'), {
            center: pos,
            zoom: 14
        });
        var infoWindow = new google.maps.InfoWindow({map: map});
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                            'Error: The Geolocation service failed.' :
                            'Error: Your browser doesn\'t support geolocation.');
    }

    window.onload = function() {
        getLocation();
    };

    document.addEventListener('DOMContentLoaded', function() {
        var successMessage = "{{ success_message }}";  // 这里替换为你的模板变量
        if (successMessage) {
            Toastify({
                text: successMessage,
                duration: 3000,  // 持续显示时间（毫秒）
                close: true,
                gravity: 'bottom',  // 可选的通知位置：'top', 'bottom', 'left', 'right'
                position: 'right',  // 在'left'或'right'位置显示时使用
                stopOnFocus: true,
            }).showToast();
        }
    });

</script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqWMFEzFkRbi6w5hGgLVN3wEAwZsTURlM&callback=initMap">
</script>

</html>